ASPECTS = {
    "Performance": [
        "quality",
        "start up",
        "features",
        "software",
        "speed",
        "windows",
        "usb devices",
        "software",
        "boot up",
        "operating system",
        "clock",
        "setup",
        "set up",
        "brand",
        "fan",
        "hard disk",
        "drivers",
        "program",
        "webcam",
        "internet",
        "motherboard",
        "system",
        "works",
        "memory",
        "hard drive",
        "speaker",
        "hardware",
        "mac",
        "temperature",
        "bluetooth",
        "windows 7",
        "cooling",
        "core",
        "i7",
        "mousepad",
        "keys",
        "multi-touch gestures",
        "processor",
        "OS",
        "performance",
        "intel",
        "ram",
        "cpu",
        "gpu",
        "hdd",
        "ssd",
        "feature",
        "dvd",
        "cd",
        "wifi",
        "storage",
        "boot",
        "plays",
        "performs",
        "access",
        "use",
        "broke",
        "disposable",
        "working",
        "froze",
        "capabilities",
        "freeze",
        "speed",
        "noiseless",
        "operate",
        "durability",
        "loud",
        "flexible",
        "fast",
        "first-class",
        "outstanding",
        "unresponsiveness",
        "well-behaved",
        "unresponsive",
        "slow",
        "powerful",
        "simple",
        "camera",
        "applications",
        "power",
    ],
    "Battery Life": [
        "cord",
        "battery life",
        "charge",
        "battery",
        "timer",
        "charging",
        "adapter",
        "plug",
        "lasted",
        "lasts",
    ],
    "Design": [
        "weight",
        "color",
        "style",
        "size",
        "ports",
        "design",
        "body",
        "weight",
        "look",
        "sleek",
        "look",
        "looks",
        "slim",
        "lightweight",
        "light",
        "body",
        "weight",
        "look",
        "tiny",
        "small",
        "slick",
        "nice",
        "fits",
        "attractive",
        "bulky",
        "elegant",
        "large",
        "heavy",
        "clumsy-looking",
        "shape",
        "heavier",
        "big",
        "mini",
    ],
    "Price": [
        "price tag",
        "price",
        "value",
        "cost",
        "worth",
        "cheaper",
        "cheap",
        "deal",
        "inexpensive",
        "overpriced",
        "expensive",
        "cheaply",
        "budget",
        "pricing",
        "money",
        "affordable",
    ],
    "Screen": [
        "gui",
        "resolution",
        "screen",
        "monitor",
        "display",
        "graphic",
        "image",
        "inch",
        '"',
        "hd",
        "displayed",
        "show",
        "displaying",
    ],
}
